// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bjsymtszozxgphgttnye.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJqc3ltdHN6b3p4Z3BoZ3R0bnllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDYzMTMsImV4cCI6MjA2NTU4MjMxM30.yW68RYy7obnMo6mPLd7B6aE1lndQ8gqJMiLDZc6sDFU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);